name: Audit repo
on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        description: "Node version"
        default: "16.x"
    outputs:
      audit-result:
        value: ${{ jobs.audit-repo.outputs.audit-result }}
jobs:
  audit-repo:
    name: Audit repo
    runs-on: ubuntu-latest
    outputs:
      audit-result: ${{steps.run-audit.outputs.result}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: npm install, build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: run auditjs
        id: run-audit
        shell: bash {0} # has to be used, or auditjs will cause whole job to fail if vulnerabilities are present
        run: |
          result=$(npx auditjs ossi --q --json)
          oneLineResult=$(echo $result | paste -sd " " -)
          echo "::set-output name=result::$oneLineResult"
