name: Build Angular App
on:
  workflow_call:
    inputs:
      download-path:
        description: "The download path for the source folder"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: npm install and build
        run: |
          sudo npm install -g @angular/cli
          npm install --force
          ng build

      # keep upload for 1 day
      - name: Upload build output to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ${{ inputs.download-path }}
          retention-days: 1
