name: Build and Deploy Firebase Functions
on:
  workflow_call:
    inputs:
      project-id:
        description: "The Firebase Project ID"
        required: true
        type: string
      node-version:
        required: false
        type: string
        description: "Node version"
        default: "16.x"
    secrets:
      gcp-sa-key:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install npm packages and build functions
        run: |
          cd functions
          npm install --force
          npm run build
      # Deploy to Firebase
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.4.0
        with:
          args: deploy --only functions --project ${{ inputs.project-id }}
        env:
          GCP_SA_KEY: ${{ secrets.gcp-sa-key }}
