name: Build Angular App
on:
  workflow_call:
    inputs:
      build-env:
        required: false
        type: string
        description: "Test or Production"
        default: test
      node-version:
        required: true
        type: string
        description: "Node version"
        default: "16.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.node-version }}
      - name: npm install and build
        run: |
          sudo npm install -g @angular/cli@16.2.10
          npm install --force
          ng build -c ${{ inputs.build-env }}

      # keep upload for 1 day
      - name: Upload build output to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 1
