name: Build Firebase Functions
on:
  workflow_call:

env:
  NODE_VERSION: "16.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install npm packages and build functions
        run: |
          cd functions
          npm install --force
          npm run build
      - name: Upload build output to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: functions/lib
          path: functions/lib
          retention-days: 1
