name: Build dotNET App
on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        description: ".NET version"
        default: 6.0.x
      nugets-caching:
        required: false
        type: boolean
        default: false
        description: "Cache Nuget dependecies"
      configuration:
        required: false
        type: string
        description: "Build configuration"
        default: "Release"
      working-directory:
        required: true
        type: string
        description: "Working directory"
      test:
        required: false
        type: boolean
        default: false
        description: "Run tests after build"
    secrets:
      azure-artifacts-pat:
        required: true

env:
  OUTPUT_PATH: deployment/dist
  NUGET_FEED_NAME: 'visionist-nuget'
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/VisionistLtd/Dev/_packaging/visionist-nuget/nuget/v3/index.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        cache: ${{ inputs.nugets-caching }}
        cache-dependency-path: ${{ inputs.working-directory }}/packages.lock.json

    - name: Restore
      run: |
        dotnet nuget add source ${{ env.AZURE_ARTIFACTS_FEED_URL }} --name ${{ env.NUGET_FEED_NAME }} --username az --password ${{ secrets.azure-artifacts-pat }} --store-password-in-clear-text
        dotnet restore "${{ inputs.working-directory }}" --locked-mode
    - name: Build
      run: dotnet build "${{ inputs.working-directory }}" --configuration ${{ inputs.configuration }} --no-restore
    - name: Test
      if: ${{ inputs.test }}
      run: dotnet test
    - name: Publish
      run: dotnet publish "${{ inputs.working-directory }}" --configuration ${{ inputs.configuration }} --no-build --output "${{ env.OUTPUT_PATH }}"
    
    # keep upload for 1 day
    - name: Upload build output to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        include-hidden-files: true
        path: ${{ env.OUTPUT_PATH }}
        retention-days: 1
