name: Get slot name from branch
on:
  workflow_call:
    inputs:
      webApp:
        description: "Web App Name"
        required: true
        type: string
      branch-name:
        required: false
        type: string
        description: 'The name of the branch to process. If not provided, it will be automatically determined.'
    outputs:
      slot-name:
        value: ${{ jobs.create-deployment-slot-name.outputs.slot-name }}
jobs:
  create-deployment-slot-name:
    name: Create deployment slot name
    runs-on: ubuntu-latest
    outputs:
      slot-name: ${{ steps.truncate-branch-name.outputs.string }}
    steps:
      # Uses the provided branch name or it defaults to the current
      # branch, if empty, for the deployment slot name (legacy behaviour)
      # Uses v6
      - name: Get branch name
        if: ${{ inputs.branch-name == '' }}
        id: auto-branch-name
        uses: tj-actions/branch-names@6871f53176ad61624f978536bbf089c574dc19a2

      # Remove forward slash from name as its invalid for deployment slot name.
      # Uses v2      
      - name: Remove feature from branch name
        id: rename-branch-name
        uses: mad9000/actions-find-and-replace-string@bce4d50390d08b67e1822bd72fb54b3cf11b0ce9
        with:
          source: ${{ inputs.branch-name || steps.auto-branch-name.outputs.current_branch }}
          find: '/'
          replace: '-'

        # Calculate max slot name length - 'webApp-slotName' cannot be longer than 59 characters
      - name: Get deployment slot max name length
        id: slot-max-name-length
        run: |
          webAppLength=${#webAppName}
          slotNameMaxLength=$((58 - webAppLength))
          echo "max-length=$slotNameMaxLength" >> $GITHUB_ENV
        env:
          webAppName: ${{ inputs.webApp }}

        # Truncate branch name so site name and slot name combined are fewer than 59 characters
        # Uses v1.2.0
      - name: Truncate branch name
        id: truncate-branch-name
        uses: 2428392/gh-truncate-string-action@51c56c4b37c0f79b5f662782e22cddc712ba45b8
        with:
          stringToTruncate: ${{ steps.rename-branch-name.outputs.value }}
          maxLength: ${{ env.max-length }}
