name: Deploy To Deployment Slot
on:
  workflow_call:
    inputs:
      buildEnv:
        description: "Test or Production"
        required: true
        type: string
      webApp:
        description: "Web App Name"
        required: true
        type: string
      resourceGroup:
        description: "Resource Group"
        required: true
        type: string
      node-version:
        required: false
        type: string
        description: "Node version"
        default: "16.x"
      angular-cli-version:
        required: false
        type: string
        description: "Angular CLI version"
        default: "16.2.10"
    secrets:
      azureCredentialsTestSlots:
        required: true
      jiraUserEmail:
        required: true
      jiraBaseUrl:
        required: true
      jiraApiToken:
        required: true

jobs:
  create-slot-name:
    name: Create Slot Name
    uses: ./.github/workflows/create-slot-name.yml
    with:
      webApp: ${{ inputs.webApp }}

  build:
    name: Build Angular App
    uses: ./.github/workflows/build-angular.yml
    with:
      build-env: ${{ inputs.buildEnv }}
      node-version: ${{ inputs.node-version }}
      angular-cli-version: ${{ inputs.angular-cli-version }}
  #Only create slot once name identified
  create-slot:
    name: Create Slot
    needs: [ create-slot-name ]
    uses: ./.github/workflows/create-slot.yml
    with:
      resource-group: ${{ inputs.resourceGroup }}
      web-app: ${{ inputs.webApp }}
      slot-name: ${{ needs.create-slot-name.outputs.slot-name }}
    secrets:
      token: ${{ secrets.azureCredentialsTestSlots }}
  #Release to deployment slot once created
  release:
    needs: [ create-slot-name, create-slot, build ]
    name: Deploy to deployment slot
    uses: ./.github/workflows/release-angular-deployment-slots.yml
    with:
      web-app: ${{ inputs.webApp }}
      slot-name: ${{ needs.create-slot-name.outputs.slot-name }}
    secrets:
      token: ${{ secrets.azureCredentialsTestSlots }}
  #Once release completed, comment on jira ticket if one is identified
  comment-on-jira:
    needs: [ create-slot-name, create-slot, release ]
    name: Comment on Jira ticket
    uses: ./.github/workflows/comment_on_jira_ticket.yml
    with:
      ticketId: ${{ needs.create-slot-name.outputs.slot-name }}
      jiraMessage: |
        - *Preview link*: https://${{ inputs.webApp }}-${{ needs.create-slot-name.outputs.slot-name }}.azurewebsites.net
        - Changes have been deployed to the slot site.
        - The preview link is shareable, but will be deleted when the branch is deleted.
    secrets:
      jiraUsername: ${{ secrets.jiraUserEmail }}
      jiraHost: ${{ secrets.jiraBaseUrl }}
      jiraToken: ${{ secrets.jiraApiToken }}
