name: Deploy Firebase Functions
on:
  workflow_call:
    inputs:
      project-id:
        description: "The Firebase Project ID"
        required: true
        type: string
    secrets:
      gcp-sa-key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        # Download build artifact
      - name: Download build output from artifacts
        id: build-folder
        uses: actions/download-artifact@v3
        with:
          name: lib
          path: ./

        # Deploy to Firebase
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project ${{ inputs.project-id }}
        env:
          GCP_SA_KEY: ${{ secrets.gcp-sa-key }}