name: Create Deployment Slot
on:
  workflow_call:
    inputs:
      resource-group:
        description: "The name of the Azure resource group"
        required: true
        type: string
      web-app:
        description: "The name of the web app"
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      slot-name: ${{ steps.rename-branch-name.outputs.value }}
    steps:
      # Login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.token }}
      
      #Uses the current branch as the deployment slot name
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6
      
      #Remove feature and forward slash from name as its invalid
    - name: Remove feature from branch name
      id: rename-branch-name
      uses: mad9000/actions-find-and-replace-string@2
      with:
        source: ${{ steps.branch-name.outputs.current_branch }}
        find: 'feature/'
        replace: ''
      
      #Create the deployment slot
    - name: Create slot
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az webapp deployment slot create --resource-group ${{ inputs.resource-group }}  --name ${{ inputs.web-app }} --slot ${{ steps.rename-branch-name.outputs.value }}
      
     # Sign out of Azure
    - name: Logout of Azure
      run: az logout
      if: always()
