name: Tag main branch
on:
  workflow_call:
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      # - name: Increase version and push tag
      #   uses: leonsteinhaeuser/git-tag-bump@v1.2.0
      #   with:
      #     args: '--v-prefix --auto-bump --create --lightweight'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Increase version and push tag
        uses: anothrNick/github-tag-action@1.71.0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
